[en]
title = "テスト作成中"
weight = 1
LanguageName = "JP"
contentDir = "content/english"

[ar]
title = "Jiro Sakamoto"
description = "Research and Development for Child Welfare"
contentDir = "content/arabic"
weight = 2
#LanguageDirection = "rtl" 
LanguageName = "EN"