  [[main]]
  name = "HOME"
  identifier = "home"
  weight = 100
  url = "/ar"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/ar/post"

  [[main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/ar/about"

  [[main]]
  name = "Contact"
  weight = 400
  identifier = "contact"
  url = "/ar/contact"