baseURL = "https://mrunadon.github.io/blogdown_page/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Jiro Sakamoto"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "docs"


# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true


author = "Jiro Sakamoto"
description = "Research and Development for Child Welfare"
profilePicture = "images/profile.jpg"

copyright = "2020-2021"

# contact setteing
#[params]
contactFormAction = "https://formspree.io/f/whitesnow1751@gmail.com"

